# /netlify.toml  ← must live at the project root

[build]
  publish   = "design"                          # your static site lives in design/
  command   = "echo 'Skipping build; static files only.'"  # no build step

[functions]
  directory = "design/netlify/functions"        # where your Netlify Functions live

[[redirects]]
  from    = "/api/*"
  to      = "https://iwkdznjqfbsfkscnbrkc.supabase.co/functions/v1/:splat"
  status  = 200
  force   = true
[build]
  # specify the Node version Netlify will use
  node_version = "18"

  # if you have a build command, put it here; for a static site you can use "npm run build"
  command = "npm run build"
  publish = "."

# (Optional) If you need environment variables, secrets, etc.
