[build]
  publish = "design"
  command = "echo 'Skipping build; static files only.'"

[[redirects]]
  from    = "/api/*"
  to      = "https://iwkdznjqfbsfkscnbrkc.supabase.co/functions/v1/:splat"
  status  = 200
  force   = true

[functions]
  directory = "netlify/functions"
