# netlify.toml

[build]
  # No build step needed for static assets
  command = "echo 'Skipping build—static site'"
  # Publish the root (where your HTML/CSS/JS live)
  publish = "."

# Tell Netlify exactly where to find your functions
[functions]
  directory = "netlify/functions"

[build.environment]
  # Pin to a Netlify-supported Node version
  NODE_VERSION = "18"

# (Optional) If you prefer to store env vars in this file instead of the UI:
[context.production.environment]
  SUPABASE_URL             = "https://iwkdznjqfbsfkscnbrkc.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3a2R6bmpxZmJzZmtzY25icmtjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDYyOTY4OCwiZXhwIjoyMDY2MjA1Njg4fQ.HPkLtB4-tf6R_4HtyhJVJ1iixIMAY_FVUDqjhHKymRw"
