[build]
  # No build command needed for static HTML/CSS/JS
  command = "echo 'Skipping build—static site'"
  # Publish the root of your repo (where your index.html lives)
  publish = "."

[build.environment]
  # Pin to a Netlify-supported Node version (even if you don't run JS)
  NODE_VERSION = "18"
