# netlify.toml

[build]
  publish = "."                      # your deploy folder (root for static HTML/JS)
  command = "echo 'Skipping build; static files only.'"  # no build step

[[redirects]]
  from    = "/api/*"  
  to      = "https://iwkdznjqfbsfkscnbrkc.supabase.co/functions/v1/:splat"
  status  = 200
  force   = true
