# netlify.toml

[build]
  publish = "design"                      # serve your dashboard from design/
  command = "echo 'Skipping build; static files only.'"  # no build step

[[redirects]]
  from    = "/api/*"  
  to      = "https://iwkdznjqfbsfkscnbrkc.supabase.co/functions/v1/:splat"
  status  = 200
  force   = true

[functions]
  directory = "design/netlify/functions"  # <-- point Netlify at your functions
